FROM wiiuenv/devkitppc:20220806

WORKDIR build
COPY . .
RUN make clean && make && mkdir -p /artifacts/wums && cp -r lib /artifacts/wums && cp -r include /artifacts/wums && cp -r share /artifacts/wums
WORKDIR /artifacts

FROM scratch as libwums
COPY --from=0 /artifacts /artifacts

FROM wiiuenv/devkitppc:20220806

COPY --from=libwums /artifacts $DEVKITPRO

WORKDIR project
