name: Publish Docker
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get release version
      id: get_release_tag
      run: echo ::set-env name=RELEASE_VERSION::$(echo $(date '+%Y%m%d'))
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: wiiuenv/wiiumodulesystem
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
        cache: true
        tags: "latest, ${{ env.RELEASE_VERSION }}"